##### Menu
menu:
  首页: /
  归档: /archives
## you can create `tags` and `categories` folders in `../source`.
## And create a `index.md` file in each of them.
## set `front-matter`as
## layout: tags (or categories)
## title: tags (or categories)
## ---

#### Widgets
widgets: 
- category
- tag
- links
- rss
- tagcloud
## provide six widgets:category,tag,rss,archive,tagcloud,links.
## modify links in `/layout/_widget/links.ejs`.

#### RSS
rss:  atom.xml ## RSS address.

#### Image
imglogo:
  enable: false             ## display image logo true/false.
  src: img/logo.svg        ## `.svg` and `.png` are recommended,please put image into the theme folder `/coney/source/img`.
favicon: img/favicon.ico   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/coney/source/img`.     

#### Author Avatar Picture
author_img_enable: true ## display author avatar picture
dataURI: false
## if the picture's format is dataURI please set the value to true,otherwise set the value to false.
## convert an image into base 64 data URIs http://websemantics.co.uk/online_tools/image_to_data_uri_convertor/ .
author_img_data: ''
## paste the dataURI in ONE LINE and included it by ''.
author_img: img/coney.png ## size:220px*220px.
## if the picture's format is `.png` or `.jpg`  instead of dataURI,you should set the `dataURI` value to false.

#### Font
ShowCustomFont: true  
## you can change custom font in `variable.styl` and `font.styl` which in the theme folder `/coney/source/css`.

#### Toc
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.
## you can set both of the value to true of neither of them.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.

#### Fancybox
fancybox: false 
## if you use gallery post or want use fancybox please set the value to true.
## if you want use fancybox in ANY post please copy the file `fancybox.js`.
## in theme folder `/coney/scripts` to your hexo blog folder `../scritps`.

#### Author information
author:
  google_plus:    ## eg:116338260303228776998 for https://plus.google.com/u/0/116338260303228776998
  weibo:      ## e.g. 436062867 for http://weibo.com/436062867
  twitter:    ## e.g. gengbiaosky for https://twitter.com/yangjiansky
  github:     ## e.g. coneycode for https://github.com/coneycode
  facebook:   ## e.g. gengbiao for https://favebook.com/yangjian
  tsina:      ## e.g. 1664838973  Your weibo ID,It will be used in share button.
  zhihu:     # coneylife, now it is no icon, I have push an issue to Font Awesome.

#### Comment
duoshuo: 
  enable: true  ## duoshuo.com
  short_name:  ## e.g. coney,duoshuo short name.

#### Share button
jiathis:
  enable: false ## if you use jiathis as your share tool,the built-in share tool won't be display.
  id:    ## e.g. 1501277 your jiathis ID. 
  tsina: ## e.g. 1664838973 Your weibo id,It will be used in share button.

####Baidu Analytics
baidu_analytics:
  enable: true
  id: 391982416296a0d54221f59fe35250d4 # your baidu analytics id

####Baidu Share
baidu_share:
  enable: true
  color: 4

theme_color:
    background: "#dddddd"
    font: "#817c7c"
    theme: '#ea6753'
    footer: "#ddd"
 ####Baidu search 
baidu_search:
  enable: true
  id: 
  site: http://zhannei.baidu.com/cse/search  #your can change your site instead the default site

google_analytics:
  enable: true
  id:   ## e.g. UA-55273525-1 your google analytics ID.
  site: ## e.g. gengbiao.me your google analytics site or set the value as auto.
## You MUST upgrade to Universal Analytics first!
## https://developers.google.com/analytics/devguides/collection/upgrade/?hl=zh_CN

####background music 
background_music:
  enable: false
  src: 
#### Custom Search
google_cse: 
  enable: false
  cx:   ## e.g. 010584917530731754670:91c2z8qybp0 your Custom Search ID
## https://www.google.com/cse/ 
## To enable the custom search You must create a "search" folder in '/source' and a "index.md" file
## set the 'front-matter' as
## layout: search 
## title: search
## ---

